platform :osx, '10.11'
use_frameworks!

target 'TB_Client_Admin' do

pod 'Alamofire', '~> 3.0'

pod 'KeychainSwift', '~> 3.0'

pod 'ObjectMapper', '~> 1.3'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end

target 'TB_Client_AdminTests' do

end

target 'TB_Client_AdminUITests' do

end
